version: '3.8'

services:
  expr01:
    container_name: expr01
    env_file: ./docker/env/expr01.env
    environment:
      # this is needed in the init.sh script
      - APP_NAME=${APP_NAME_EXPR01}
      - APP_PORT=${APP_PORT_EXPR01}
    build:
      context: .
      args:
        # used in the dockerfile
        - APP_NAME=${APP_NAME_EXPR01}
        - NODE_VERSION=${NODE_VERSION_EXPR01}
      dockerfile: ./docker/nodejs/dockerfile
    command: bash -c "sh /home/init.sh"
    ports:
      - "${LOCAL_APP_PORT_EXPR01}:${APP_PORT_EXPR01}"
    volumes:
      - ./app/${APP_NAME_EXPR01}:/home/app/${APP_NAME_EXPR01}
      - ./docker/nodejs/init.sh:/home/init.sh
    networks:
      - exprjsnetwork

  expr02:
    container_name: expr02
    env_file: ./docker/env/expr02.env
    environment:
      - APP_NAME=${APP_NAME_EXPR02}
      - APP_PORT=${APP_PORT_EXPR01}
    build:
      context: .
      args:
        - APP_NAME=${APP_NAME_EXPR02}
        - NODE_VERSION=${NODE_VERSION_EXPR02}
      dockerfile: ./docker/nodejs/dockerfile
    command: bash -c "sh /home/init.sh"
    ports:
      - "${LOCAL_APP_PORT_EXPR02}:${APP_PORT_EXPR02}"
    volumes:
      - ./app/${APP_NAME_EXPR02}:/home/app/${APP_NAME_EXPR02}
      - ./docker/nodejs/init.sh:/home/init.sh
    networks:
      - exprjsnetwork

    # Repeat exprs as needed
    # Also add other services at will
  
networks:
  exprjsnetwork:
